//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public string MenuID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MenuPhoto { get; set; }
        public decimal Carlorie { get; set; }
    }
}
