//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalMenu
    {
        public string PersonId { get; set; }
        public string MenuID { get; set; }
        public string Id { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
